Watcher Running in C:\Users\PicoProbeUser\Documents\MicroscopeData\Brace\transfers/

{'input': {'transfer_source_endpoint_id': '387aaf6e-3302-11ee-9200-5b20905a64b1', 'transfer_destination_endpoint_id': '300ef593-e55e-4bc1-ab21-6d26d82c3b99', 'transfer_source_path': 'MicroscopeData/Brace/transfers/2023081040-700kx MultiFrams 991ms 600F Counting & FFI mode Falcon 700 kx 1819.emd', 'transfer_destination_path': 'PicoProbeTestEndpoint/08-18-PicoProbeUser-temporal-test/20230818-183745/2023081040-700kx MultiFrams 991ms 600F Counting & FFI mode Falcon 700 kx 1819.emd', 'transfer_recursive': False, 'yolo_model_path': '/lus/eagle/projects/CVD-Mol-AI/braceal/tmp-space/best-yolo.pt', 'funcx_endpoint_compute': 'd8e16504-eaab-44b6-aa56-ff7d1b6040a3', 'funcx_endpoint_non_compute': 'f53c4fe3-1293-4baa-bdb0-118fab4e56ef', 'publishv2': {'dataset': '/lus/eagle/projects/APSDataAnalysis/PICOPROBE/PicoProbeTestEndpoint/08-18-PicoProbeUser-temporal-test/20230818-183745', 'destination': '/lus/eagle/projects/APSDataAnalysis/PICOPROBE/PicoProbeTestEndpoint/08-18-PicoProbeUser-temporal-test/20230818-183745', 'source_collection': '300ef593-e55e-4bc1-ab21-6d26d82c3b99', 'destination_collection': '300ef593-e55e-4bc1-ab21-6d26d82c3b99', 'index': '06625170-a9ee-4d68-b8dc-2480c9407966', 'metadata': {}, 'ingest_enabled': True, 'transfer_enabled': False, 'visible_to': ['public']}}}
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\managers\flows_manager.py", line 283, in sync_flow
    self.check_flow()
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\managers\flows_manager.py", line 265, in check_flow
    'No flow_id set on flow manager and no id tracked in storage.')
gladier.exc.NoFlowRegistered: No flow_id set on flow manager and no id tracked in storage.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\watchdog\observers\api.py", line 204, in run
    self.dispatch_events(self.event_queue)
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\watchdog\observers\api.py", line 380, in dispatch_events
    handler.dispatch(event)
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\watchdog\events.py", line 275, in dispatch
    self.on_any_event(event)
  File ".\examples\temporal_application\main.py", line 116, in on_any_event
    self.start_flow(flow_input, run_label=f"Temporal {file.name}")
  File "e:\picoprobe user local data\brace\software\picoprobedataflow\picoprobe\utils.py", line 152, in start_flow
    flow = self.flow_client.run_flow(flow_input=flow_input, label=run_label)
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\client.py", line 323, in run_flow
    self.sync_flow()
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\client.py", line 259, in sync_flow
    self.flows_manager.sync_flow()
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\managers\flows_manager.py", line 285, in sync_flow
    self.on_change(self, exc)
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\managers\flows_manager.py", line 35, in ensure_flow_registered
    flows_manager_instance.register_flow()
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\gladier\managers\flows_manager.py", line 325, in register_flow
    **flow_kwargs).data
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\globus_automate_client\flows_client.py", line 366, in deploy_flow
    return self.post(url, data=req_body, **kwargs)
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\globus_sdk\client.py", line 170, in post
    encoding=encoding,
  File "E:\PicoProbe User Local Data\Brace\software\PicoProbeDataFlow\env\lib\site-packages\globus_sdk\client.py", line 319, in request
    raise self.error_class(r)
globus_sdk.exc.api.GlobusAPIError: ('POST', 'https://flows.globus.org/flows', 'Bearer', 403, 'Error', 'FORBIDDEN')